import { supabase } from "@/lib/supabase";
import { export191Row } from "@/lib/scoring/export191";
import { stateAt, teamSetupsFromLineup } from "@/lib/scoring/engine";
import { LocalGame, localStore } from "@/lib/scoring/local-store";

// Existing scoring sync flow shared by the top screen and game management.
export async function syncScoringGame(game: LocalGame, userId: string) {
  const { error: gameError } = await supabase.from("scoring_games").upsert({ id: game.id, display_game_number: game.display_game_number, game_date: game.game_date, game_time: game.game_time, stadium_id: game.stadium_id ?? null, weather_id: game.weather_id ?? null, method: game.method, home_team_id: game.home_team_id, away_team_id: game.away_team_id, season: game.season, kind: game.kind, week: game.week, day: game.day, game_number: game.game_number, umpire: game.umpire ?? null, tags: game.tags, status: game.status, created_by: userId }, { onConflict: "id" });
  if (gameError) throw gameError;
  if (game.lineup?.length) { const { error } = await supabase.from("scoring_lineups").upsert(game.lineup.map((row:any) => ({game_id:game.id,...row})), {onConflict:"game_id,team_id,slot"}); if(error) throw error; }
  const plays=await localStore.plays(game.id);
  if(plays.length){const device=await localStore.deviceId();const {error}=await supabase.from("scoring_plays").upsert(plays.map(p=>({game_id:game.id,seq:p.seq,input_event:p.page,page_state:{},client_mutation_id:p.client_mutation_id,device_id:device})),{onConflict:"game_id,client_mutation_id"});if(error)throw error;}
  const [{data:home},{data:away}]=await Promise.all([supabase.from("opponent_teams").select("name").eq("id",game.home_team_id).single(),supabase.from("opponent_teams").select("name").eq("id",game.away_team_id).single()]);
  const existing=await supabase.from("games").select("id").eq("date",`${game.game_date}T00:00:00`).eq("season",game.season).eq("kind",game.kind).eq("game_number",game.game_number).maybeSingle();
  if(!existing.data){const {error}=await supabase.from("games").insert({id:game.id,date:`${game.game_date}T${game.game_time}:00`,season:game.season,kind:game.kind,week:Number(game.week),game_number:game.game_number,away_team:away?.name??game.away_name??"",home_team:home?.name??game.home_name??"",scorekeeper:game.umpire??null});if(error)throw error;}else{const {error}=await supabase.from("games").update({date:`${game.game_date}T${game.game_time}:00`,away_team:away?.name??game.away_name??"",home_team:home?.name??game.home_name??"",scorekeeper:game.umpire??null}).eq("id",existing.data.id);if(error)throw error;}
  const {error:delError}=await supabase.from("pitches").delete().eq("game_id",game.id);if(delError)throw delError;
  if(plays.length){const teamNames:[string,string]=[away?.name??game.away_name??"",home?.name??game.home_name??""];const setup=teamSetupsFromLineup(game.lineup as any,[game.away_team_id,game.home_team_id],teamNames);const lineupNames:[string[],string[]]=[setup[0].order.map(no=>String((game.lineup as any[]).find(x=>x.team_id===game.away_team_id&&Number(x.uniform_no)===no)?.player_snapshot?.name??"")),setup[1].order.map(no=>String((game.lineup as any[]).find(x=>x.team_id===game.home_team_id&&Number(x.uniform_no)===no)?.player_snapshot?.name??""))];const lineupPositions:[string[],string[]]=[setup[0].pos.map(String),setup[1].pos.map(String)];const hands:[string[],string[]]=[setup[0].bats.map(x=>x==="左"?"L":x==="両"?"S":"R"),setup[1].bats.map(x=>x==="左"?"L":x==="両"?"S":"R")];const rows=plays.map((play,index)=>{const st=stateAt(index,plays.map(x=>x.page),setup);const row=export191Row(st,play.page,{dateTime:`${game.game_date} ${game.game_time}:00`,season:game.season,kind:game.kind,week:game.week,day:game.day,gameNumber:game.game_number,homeTeam:teamNames[1],awayTeam:teamNames[0],umpire:game.umpire,pitcherNames:["",""],catcherNames:["",""],lineupNames,lineupPositions,hands,pitcherHands:["R","R"]},play.seq,{result:play.page.res?.label,pitchType:play.page.pitch_type??undefined,pitchSpeed:play.page.ball_speed?Number(play.page.ball_speed):undefined,course:play.page.course??undefined,ballXY:play.page.batted_ball?[play.page.batted_ball.x,play.page.batted_ball.y]:undefined});return {game_id:game.id,play_number:Number(row[9])||play.seq,inning:Number(row[10])||1,top_bottom:String(row[11]||"表"),offense_team:String(row[182]||teamNames[0]),batter_order:Number(row[26])||null,batter_name:row[27]||null,batter_hand:row[28]||null,pitcher_name:row[32]||null,pitcher_hand:row[33]||null,catcher_name:row[35]||null,runner_1st:row[21]||null,runner_2nd:row[23]||null,runner_3rd:row[25]||null,balls:Number(row[14])||0,strikes:Number(row[13])||0,outs:Number(row[15])||0,pa_complete:row[17]||null,pitch_count:Number(row[34])||null,pitch_type:row[44]||null,pitch_speed:Number(row[55])||null,course_x:Number(row[42])||null,course_y:Number(row[43])||null,batting_result:row[45]||null,batting_result2:row[46]||null,hit_type:row[47]||null,hit_strength:row[48]||null,hit_x:Number(row[49])||null,hit_y:Number(row[50])||null,strategy:row[29]||null,strategy2:row[30]||null,strategy_result:row[31]||null,error_type:row[53]||null,fielder:row[46]||null}});const {error}=await supabase.from("pitches").insert(rows);if(error)throw error;}
  const all=await localStore.games();await localStore.saveGames(all.map(g=>g.id===game.id?{...g,synced_at:new Date().toISOString()}:g));
}
