import { useEffect, useMemo, useState } from "react";
import { Alert, Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, useWindowDimensions, View } from "react-native";
import Svg, { Circle, Line, Path, Polygon, Rect, Text as SvgText } from "react-native-svg";
import { Redirect, useLocalSearchParams } from "expo-router";
import { useAuth } from "@/hooks/use-auth";
import { supabase } from "@/lib/supabase";
import { applyPage, blank, checkCommit, GameState, Page, stateAt, TeamSetup, teamSetupsFromLineup } from "@/lib/scoring/engine";
import { localStore, LocalGame, LocalPlay } from "@/lib/scoring/local-store";

type Row = Record<string, any>;
type InputMove = import("@/lib/scoring/engine").Move & { steal?: boolean };
const BASEXY: Record<number, [number, number]> = { 0:[46,238],1:[113,238],2:[118,163],3:[46,165] };
const POSXY: Record<number,[number,number]> = { 1:[77,207],2:[32,252],3:[137,257],4:[142,197],5:[27,152],6:[87,142],7:[77,77],8:[182,107],9:[207,212] };
const PALETTE = ["#fff9db","#e6fcf5","#e7f5ff","#f3f0ff","#fff0f6","#edf2ff"];
const posNames: Record<number,string> = {1:"投",2:"捕",3:"一",4:"二",5:"三",6:"遊",7:"左",8:"中",9:"右",10:"DH"};
export default function ScoringInput() {
 const { id="" }=useLocalSearchParams<{id:string}>(); const {user,isLoading,hasRole}=useAuth(); const {width,height}=useWindowDimensions();
 const [game,setGame]=useState<LocalGame|null>(null),[pages,setPages]=useState<Page[]>([]),[results,setResults]=useState<Row[]>([]),[teams,setTeams]=useState<Row[]>([]),[roster,setRoster]=useState<Row[]>([]),[ballTypes,setBallTypes]=useState<Row[]>([]),[plans,setPlans]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [pov,setPov]=useState(false),[fielderMode,setFielderMode]=useState(true),[pickMode,setPickMode]=useState(false),[errMode,setErrMode]=useState(false),[runner,setRunner]=useState<number|null>(null),[modal,setModal]=useState<"subs"|"tb"|"home"|"end"|null>(null),[toast,setToast]=useState("");
 const [selectedRunner,setSelectedRunner]=useState<number|null>(null),[subTeam,setSubTeam]=useState(0),[subSlot,setSubSlot]=useState(0),[subPlayer,setSubPlayer]=useState(""),[focusPage,setFocusPage]=useState(0);
 useEffect(()=>{(async()=>{try{let g=(await localStore.games()).find(x=>x.id===id);if(!g){const {data}=await supabase.from("scoring_games").select("*").eq("id",id).single();if(data){const [h,a,l]=await Promise.all([supabase.from("opponent_teams").select("name").eq("id",data.home_team_id).single(),supabase.from("opponent_teams").select("name").eq("id",data.away_team_id).single(),supabase.from("scoring_lineups").select("*").eq("game_id",id)]);g={...data,home_name:h.data?.name,away_name:a.data?.name,lineup:l.data??[]} as LocalGame}}
 if(g){let lineup=(g.lineup??[]) as Row[];if(!lineup.length){const {data}=await supabase.from("scoring_lineups").select("*").eq("game_id",id);lineup=data??[]}lineup=await Promise.all(lineup.map(async row=>{if(row.player_snapshot?.name)return row;const {data}=await supabase.from("scoring_roster_players").select("id,name,bat_hand,throw_hand,primary_position_id").eq("id",row.roster_player_id).single();return {...row,player_snapshot:data}}));g.lineup=lineup;setGame(g)}
 const stored=await localStore.plays(id);setPages(stored.map(x=>x.page));const [r,t,p,b,pl,wx]=await Promise.all([supabase.from("scoring_results").select("*").eq("display_flag",true).order("show_index"),supabase.from("opponent_teams").select("id,name"),supabase.from("scoring_roster_players").select("id,name,team_id,bat_hand,throw_hand,primary_position_id,retired,show_index"),supabase.from("scoring_ball_types").select("*").eq("display_flag",true).order("show_index"),supabase.from("scoring_plans").select("*").eq("display_flag",true).gt("show_index",0).order("show_index"),supabase.from("scoring_positions").select("id,name")]);setResults(r.data??[]);setTeams(t.data??[]);setRoster(p.data??[]);setBallTypes(b.data??[]);setPlans(pl.data??[]);setLoading(false)}catch(e){setError(String(e));setLoading(false)}})()},[id]);
 const lineup=(game?.lineup??[]) as Row[]; const teamIds:[string,string]=[game?.away_team_id??"",game?.home_team_id??""];const teamNames:[string,string]=[game?.away_name??"先攻",game?.home_name??"後攻"];
 const setups=useMemo(()=>teamSetupsFromLineup(lineup as any,teamIds,teamNames),[game]);const state=useMemo(()=>stateAt(pages.length,pages,setups),[pages,game]);const editIndex=focusPage;const currentPage=pages[focusPage]??blank();const edit=(fn:(p:Page)=>void)=>setPages(prev=>{const a=[...prev];while(a.length<=focusPage)a.push(blank());fn(a[focusPage]);return a});
 const batter=state.lu[state.half].order[state.bi[state.half]],pitcher=state.lu[1-state.half].P;const offense=teamIds[state.half],defense=teamIds[1-state.half];const batterRow=lineup.find(x=>x.team_id===offense&&x.slot===state.bi[state.half]+1);const pitcherRow=lineup.find(x=>x.team_id===defense&&x.slot===10);const displayName=(row:Row|undefined,no:number)=>row?.player_snapshot?.name??roster.find(x=>x.id===row?.roster_player_id)?.name??`#${no}`;
 const preview=useMemo(()=>{const st=stateAt(editIndex,pages,setups,true);const pv=JSON.parse(JSON.stringify(st)) as GameState;if(currentPage.res||currentPage.skip||currentPage.pickoff_throw_to)applyPage(pv,currentPage);return pv},[pages,game]);
 const setErrorMsg=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2600)};
 const saveAll=async(next:Page[])=>{setPages(next);const old=await localStore.plays(id);const saved=next.slice(0,next.length-1).map((page,i)=>({seq:i+1,page,client_mutation_id:old[i]?.client_mutation_id??`edit-${Date.now()}-${i}`,created_at:old[i]?.created_at??new Date().toISOString()} as LocalPlay));await localStore.savePlays(id,saved)};
 const commit=async()=>{const p=pages[editIndex]??blank();const st=stateAt(editIndex,pages,setups,true);const msg=checkCommit(st,p);if(msg){setErrorMsg(msg);return}const after=JSON.parse(JSON.stringify(st)) as GameState;applyPage(after,p);if(after.half!==st.half&&st.outs<3){setModal("end");return}const next=[...pages];while(next.length<=editIndex)next.push(blank());await saveAll(next);setPages([...next,blank()]);setFocusPage(next.length);setPickMode(false);setRunner(null)};
 const chooseResult=(r:Row)=>edit(p=>{const ek=r.engine_kind??r.summary_code;let kind:any=/^[1-4]$/.test(String(ek))?Number(ek):ek;if(kind==="K"||kind==="KL")kind="S";if(kind==="BB")kind="B";if(kind==="HBP")kind="hbp";if(kind==="BK")kind="BK";p.res={label:r.name,kind};p.skip=false;p.pickoff_throw_to=0;p.feature=0;for(const k of Object.keys(p.ra))if(!(p.ra[+k] as InputMove|undefined)?.steal)delete p.ra[+k]});
 const setRunnerMove=(b:number,action:"out"|"back"|"steal"|"to1"|"to2"|"to3"|"home")=>edit(p=>{if(action==="back"){p.ra[b]={back:true};return}if(action==="out"){p.ra[b]={...((p.ra[b] as InputMove|undefined)?.steal?{steal:true}:{}),out:true};return}if(action==="steal"){setSelectedRunner(b);return}const to=action==="home"?4:Number(action.slice(-1));p.ra[b]={to,...(selectedRunner===b?{steal:true}:{} )};setSelectedRunner(null);if(to===4)setModal("home")});
 const chooseRunner=(b:number)=>{const act=preview;const idOn=b===0?batter:act.bases[b-1];if(b>0&&idOn==null)return;setRunner(b);setSelectedRunner(b)};
 const pitchKind=(name:string,kind:string)=>edit(p=>{if(kind==="F"){p.flags=p.flags.includes(name)?p.flags.filter(x=>x!==name):[...p.flags,name];return}const r=results.find(x=>x.name===name)||{name,engine_kind:kind};chooseResult(r)});
 const pickPlayer=(team:number,slot:number)=>{setSubTeam(team);setSubSlot(slot);setSubPlayer("");setModal("subs")};
 const applySub=()=>{const player=roster.find(x=>x.id===subPlayer);if(!player)return;edit(p=>{p.subs.push({t:subTeam as 0|1,slot:subSlot===9?"P":subSlot,no:Number(player.uniform_no??player.show_index)||slotNumber(subSlot),bats:player.bat_hand==="L"?"左":player.bat_hand==="S"?"両":"右",throws:player.throw_hand==="L"?"左":"右",pos:player.primary_position_id})});setModal(null)};
 function slotNumber(slot:number){const row=lineup.find(x=>x.team_id===teamIds[subTeam]&&(slot===9?x.slot===10:x.slot===slot+1));const n=Number(row?.uniform_no??row?.player_snapshot?.uniform_no);return n||slot+1}
 const fieldInPlay=!!currentPage.res&&(typeof currentPage.res.kind==="number"||["out","sac","sf","e","fc"].includes(String(currentPage.res.kind)));
 const scale=Math.min(width/1512,height/771);const stageW=1512*scale,stageH=771*scale;
 if(isLoading||loading)return <View style={s.center}><Text>読み込み中…</Text></View>;if(!user)return <Redirect href="/login"/>;if(!hasRole("analyst")&&!hasRole("admin"))return <Redirect href="/(tabs)"/>;if(!game)return <View style={s.center}><Text>試合が見つかりません。{error}</Text></View>;
 const Btn=({label,onPress,x,y,w=78,h=30,bg="#fff",fg="#212529",active=false}:any)=><TouchableOpacity onPress={onPress} style={[s.abs,{left:x,top:y,width:w,height:h,backgroundColor:active?"#20c997":bg,borderColor:active?"#20c997":"#ced4da"}]}><Text numberOfLines={1} style={{fontSize:Math.max(9,13*scale),color:active?"#fff":fg,textAlign:"center"}}>{label}</Text></TouchableOpacity>;
 const Field=()=> <Svg width={381*scale} height={381} viewBox="0 0 280 280"><Rect width="280" height="280" fill="#3f6b16"/><Path d="M40 240 L40 -22 A262 262 0 0 1 302 240 Z" fill="#7cb342"/><Path d="M40 240 L40 112 A128 128 0 0 1 168 240 Z" fill="#4d7f1d"/><Line x1="40" y1="240" x2="40" y2="0" stroke="white"/><Line x1="40" y1="240" x2="280" y2="240" stroke="white"/>{Object.entries(BASEXY).map(([b,[x,y]])=><Rect key={b} x={x-8} y={y-8} width="16" height="16" fill="white" onPress={()=>runner!==null&&setRunnerMove(runner,+b===0?"home":`to${b}` as any)}/>)}{Object.entries(POSXY).map(([pos,[x,y]])=><Circle key={pos} cx={x} cy={y} r="10" fill="#343a40" stroke="#eee" onPress={()=>{if(errMode){edit(p=>p.catch_fielder.push({pos:+pos,err:"ミスプレイ"}));setErrMode(false)}else if(fielderMode)edit(p=>p.catch_fielder.push(+pos))}}/>)}{currentPage.batted_ball&&<Line x1="46" y1="238" x2={currentPage.batted_ball.x} y2={currentPage.batted_ball.y} stroke="#e03131"/>}{[0,1,2,3].map(b=>{const id=b===0?batter:preview.bases[b-1];if(id==null&&b!==0)return null;const [x,y]=BASEXY[b];return <Circle key={b} cx={x} cy={y} r="9" fill={currentPage.ra[b]?.out?"#f03e5e":currentPage.ra[b]?.to?"#20c997":"white"} stroke="#333" onPress={()=>chooseRunner(b)}/>})}</Svg>;
 const Zone=()=> <Svg width={200} height={250} viewBox="0 0 200 250" onPress={(e:any)=>{const {locationX,locationY}=e.nativeEvent;edit(p=>p.course=[pov?200-locationX:locationX,locationY/scale])}}><Rect width="200" height="250" fill="white"/>{Array.from({length:11},(_,i)=><Line key={`v${i}`} x1={i*20} x2={i*20} y1="0" y2="250" stroke="#999" strokeWidth=".6"/>)}{Array.from({length:13},(_,i)=><Line key={`h${i}`} x1="0" x2="200" y1={i*20.5} y2={i*20.5} stroke="#999" strokeWidth=".6"/>)}<Rect x="38.5" y="51" width="122.5" height="154" fill="none" stroke="#111" strokeWidth="2"/>{currentPage.course&&<Circle cx={pov?200-currentPage.course[0]:currentPage.course[0]} cy={currentPage.course[1]} r="6" fill="#fd7e14"/>}</Svg>;
 const pitchBtns=["空振","見送","ボール","ファウル","逆球","ワンバウンド","クイック","ﾜｲﾙﾄﾞﾋﾟｯﾁ","ﾊﾟｽﾎﾞｰﾙ","申告敬遠","ボーク"];
 return <View style={s.screen}><ScrollView horizontal contentContainerStyle={{width:stageW,height:stageH}}><View style={{width:1512,height:771,transform:[{scale}],transformOrigin:"top left"} as any}>
 <View style={s.top}><Text style={s.title}>{game.display_game_number}　{game.away_name} vs {game.home_name}　{state.inn}回{state.half===0?"表":"裏"}</Text><Text style={s.score}>{state.score[0]} - {state.score[1]}　B{preview.b} S{preview.s} O{preview.outs}　{state.bases.map(v=>v??"－").join(" / ")}</Text></View>
 <Text style={[s.info,{left:65,top:73}]}>投手 {displayName(pitcherRow,pitcher)}　/　打者 {displayName(batterRow,batter)}　　球数 {state.pcount[pitcher]??0}</Text>
 <Text style={[s.info,{left:660,top:73}]}>捕球順 {currentPage.catch_fielder.join(" → ")}</Text>
 <TouchableOpacity style={[s.button,{left:136,top:17,width:96}]} onPress={()=>setPov(!pov)}><Text>{pov?"● 投手目線":"○ 投手目線"}</Text></TouchableOpacity>
 <TouchableOpacity style={[s.button,{left:231,top:17}]} onPress={()=>setModal("tb")}><Text>タイブレーク</Text></TouchableOpacity>
 <TouchableOpacity style={[s.button,{left:1027,top:17,width:106,backgroundColor:"#3b5bdb"}]} onPress={()=>setFocusPage(v=>Math.max(0,v-1))}><Text style={{color:"white"}}>◀ 前のページ</Text></TouchableOpacity>
 <TouchableOpacity style={[s.button,{left:1141,top:17,width:112,backgroundColor:"#3b5bdb"}]} onPress={()=>setFocusPage(Math.max(0,pages.length-1))}><Text style={{color:"white"}}>最後のページ ⏭</Text></TouchableOpacity>
 <TouchableOpacity style={[s.button,{left:1260,top:17,width:74,backgroundColor:"#4c9aff"}]} onPress={()=>setModal("subs")}><Text style={{color:"white"}}>選手交代</Text></TouchableOpacity>
 <Text style={[s.info,{left:960,top:23}]}>ページ {editIndex+1} / {pages.length}</Text>
 <View style={[s.box,{left:88,top:152,width:125,height:64}]}><Text>投手/打者 左右</Text><TouchableOpacity onPress={()=>edit(p=>p.handB="右")}><Text>右　　</Text></TouchableOpacity><TouchableOpacity onPress={()=>edit(p=>p.handB="左")}><Text>左　　両打ち切替</Text></TouchableOpacity></View>
 <View style={[s.box,{left:250,top:152,width:438,height:63}]}>{["外角高","高め","内角高","外角","真ん中","内角"].map((v,i)=><TouchableOpacity key={v} style={[s.button,{position:"relative",left:0,top:0,width:72,height:30,backgroundColor:currentPage.catcher_mitt_position===i+1?"#20c997":"white"}]} onPress={()=>edit(p=>p.catcher_mitt_position=p.catcher_mitt_position===i+1?0:i+1)}><Text>{v}</Text></TouchableOpacity>)}</View>
 {ballTypes.map((b,i)=><TouchableOpacity key={b.id} style={[s.button,{left:100+(i%2)*84,top:224+Math.floor(i/2)*52,width:76,height:48,backgroundColor:currentPage.pitch_type===b.name?"#4c9aff":"white"}]} onPress={()=>edit(p=>p.pitch_type=p.pitch_type===b.name?null:b.name)}><Text>{b.name_s||b.name}</Text></TouchableOpacity>)}
 <View style={{position:"absolute",left:362,top:220}}><Zone/></View>
 <View style={[s.box,{left:100,top:594,width:113,height:40}]}><TextInput value={currentPage.ball_speed||"1"} keyboardType="numeric" style={{fontSize:20}} onChangeText={v=>edit(p=>p.ball_speed=v.slice(0,3))}/></View>
 {["7","8","9","4","5","6","1","2","3","C","0"].map((d,i)=><Btn key={i} label={d} x={100+(i%3)*38} y={638+Math.floor(i/3)*30} w={38} onPress={()=>edit(p=>{p.ball_speed=d==="C"?"":(p.ball_speed||"1")+d})}/>)}
 {pitchBtns.map((v,i)=><Btn key={v} label={v} x={i<4?221:i<7?342:463} y={594+(i<4?i:i<7?i-4:i-7)*38} w={113} bg={PALETTE[i%PALETTE.length]} active={currentPage.flags.includes(v)||currentPage.res?.label===v} onPress={()=>pitchKind(v,["空振","見送"].includes(v)?"S":v==="ボール"?"B":v==="ファウル"?"FO":v==="申告敬遠"?"IBB":v==="ボーク"?"BK":"F")}/>)}
 <Text style={[s.preview,{left:588,top:600}]}>{currentPage.res?.label??(currentPage.skip?"打席スキップ":"入力結果")}</Text><TouchableOpacity style={[s.commit,{left:588,top:638}]} onPress={commit}><Text style={{fontSize:24}}>確定</Text></TouchableOpacity><TouchableOpacity style={[s.button,{left:588,top:694,width:62}]} onPress={()=>edit(p=>Object.assign(p,blank()))}><Text>クリア</Text></TouchableOpacity><TouchableOpacity style={[s.button,{left:654,top:694,width:98,backgroundColor:currentPage.skip?"#ffd43b":"#fff9db"}]} onPress={()=>edit(p=>{p.skip=!p.skip;p.res=null})}><Text>打席スキップ</Text></TouchableOpacity>
 <View style={{position:"absolute",left:865,top:182}}><Field/></View>
 <TouchableOpacity style={[s.button,{left:873,top:190,width:95}]} onPress={()=>setFielderMode(!fielderMode)}><Text>{fielderMode?"野手タップON":"野手タップOFF"}</Text></TouchableOpacity><TouchableOpacity style={[s.button,{left:764,top:284,width:92}]} onPress={()=>setPickMode(!pickMode)}><Text>{pickMode?"牽制先を選択":"牽制"}</Text></TouchableOpacity><TouchableOpacity style={[s.button,{left:764,top:318,width:92}]} onPress={()=>setErrMode(!errMode)}><Text>{errMode?"エラー対象":"エラー"}</Text></TouchableOpacity>
 {["ゴロ","フライ","ライナー"].map((x,i)=><TouchableOpacity key={x} style={[s.button,{left:764,top:352+i*34,width:92,opacity:fieldInPlay?1:.45}]} onPress={()=>edit(p=>p.feature=p.feature===i+1?0:i+1)}><Text>{x}</Text></TouchableOpacity>)}{["A","B","C","X"].map((x,i)=><TouchableOpacity key={x} style={[s.button,{left:764+(i%2)*46,top:454+Math.floor(i/2)*30,width:46}]} onPress={()=>edit(p=>p.rank=String(i===3?0:i+1))}><Text>{x}</Text></TouchableOpacity>)}
 {results.filter(r=>[1,2,3,4].includes(Number(r.engine_kind))||["out","fc","e","sac","sf","hbp","io","IBB"].includes(String(r.engine_kind))).map((r,i)=><TouchableOpacity key={r.id} style={[s.button,{left:774+(i%4)*66,top:578+Math.floor(i/4)*32,width:64,backgroundColor:currentPage.res?.label===r.name?"#f03e5e":"white"}]} onPress={()=>chooseResult(r)}><Text numberOfLines={1}>{r.name_s||r.name}</Text></TouchableOpacity>)}
 {plans.filter(x=>x.show_index===1||x.show_index===2||x.show_index===3).map((p,i)=><TouchableOpacity key={p.id} style={[s.button,{left:760,top:182+i*34,width:100}]} onPress={()=>edit(q=>q.plan[p.division===8?"バント":p.division===3?"盗塁":"エンドラン"]=q.plan[p.division===8?"バント":p.division===3?"盗塁":"エンドラン"]===p.name?undefined:p.name)}><Text numberOfLines={1}>{p.name_s||p.name}</Text></TouchableOpacity>)}
 {roster.filter(x=>x.team_id===offense&&!x.retired).slice(0,9).map((x,i)=><Text key={x.id} style={{position:"absolute",left:1360,top:182+i*34,fontSize:12}}>{i+1}. {x.name}</Text>)}
 <TouchableOpacity style={[s.button,{left:772,top:665,width:120}]} onPress={()=>edit(p=>p.catch_fielder=[])}><Text>捕球順を消去</Text></TouchableOpacity><TextInput placeholder="メモ" value={currentPage.memo} onChangeText={v=>edit(p=>p.memo=v)} style={[s.memo,{left:1104,top:576}]}/>
 <View style={[s.bottomScore,{left:65,top:690}]}><Text>{game.away_name} {preview.score[0]}　{game.home_name} {preview.score[1]}　{preview.inn}回{preview.half===0?"表":"裏"}　B{preview.b} S{preview.s} O{preview.outs}</Text></View>
 {toast!==""&&<Text style={[s.toast,{left:530,top:43}]}>{toast}</Text>}
 </View></ScrollView>
 <Modal visible={modal!==null} transparent animationType="fade" onRequestClose={()=>setModal(null)}><View style={s.scrim}><View style={s.dialog}><Text style={s.dialogTitle}>{modal==="subs"?"選手交代":modal==="tb"?"タイブレーク":modal==="home"?"本塁の記録":"イニング終了確認"}</Text>{modal==="subs"?<><Text>チーム・打順を選び、交代選手を指定します。</Text><View style={s.row}>{[0,1].map(t=><TouchableOpacity key={t} style={s.button} onPress={()=>setSubTeam(t)}><Text>{teamNames[t]}</Text></TouchableOpacity>)}</View><ScrollView style={{maxHeight:170}}>{lineup.filter(x=>x.team_id===teamIds[subTeam]).map(x=><TouchableOpacity key={x.id??x.slot} style={s.pickRow} onPress={()=>{setSubSlot(x.slot===10?9:x.slot-1);setSubPlayer("")}}><Text>{x.slot===10?"投手":`${x.slot}番`}　{displayName(x,Number(x.uniform_no)||x.slot)}</Text></TouchableOpacity>)}</ScrollView><ScrollView style={{maxHeight:180}}>{roster.filter(x=>x.team_id===teamIds[subTeam]&&!x.retired).map(x=><TouchableOpacity key={x.id} style={s.pickRow} onPress={()=>setSubPlayer(x.id)}><Text style={{color:subPlayer===x.id?"#0a7ea4":"#222"}}>{x.name}　{posNames[x.primary_position_id]??""}</Text></TouchableOpacity>)}</ScrollView></>:modal==="tb"?<><Text>延長時の打者と走者を指定できます。</Text><View style={s.row}>{[0,1,2].map((b)=><TouchableOpacity key={b} style={s.button} onPress={()=>edit(p=>p.tb={bi:b,r:[(b+8)%9,(b+7)%9,null],b:0,s:0,o:0})}><Text>{b+1}番起点</Text></TouchableOpacity>)}</View></>:modal==="home"?<Text>本塁へ向かう走者について、得点・アウト・打点を画面上で選択できます。</Text>:<Text>3アウトになりました。次のイニングへ進みます。</Text>}<View style={s.row}><TouchableOpacity style={s.button} onPress={()=>setModal(null)}><Text>閉じる</Text></TouchableOpacity>{modal==="subs"&&<TouchableOpacity style={s.button} onPress={applySub}><Text>交代を登録</Text></TouchableOpacity>}<TouchableOpacity style={s.button} onPress={commit}><Text>確定</Text></TouchableOpacity></View></View></View></Modal>
 </View>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:"#fff",alignItems:"center",justifyContent:"center"},center:{flex:1,alignItems:"center",justifyContent:"center"},top:{position:"absolute",left:94,top:47,width:1320,height:52,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},title:{fontSize:20,fontWeight:"700",color:"#18324a"},score:{fontSize:16,fontWeight:"700"},info:{position:"absolute",fontSize:14,color:"#343a40"},button:{position:"absolute",height:30,borderWidth:1,borderColor:"#ced4da",borderRadius:4,backgroundColor:"white",alignItems:"center",justifyContent:"center",paddingHorizontal:4},box:{position:"absolute",borderWidth:1,borderColor:"#ced4da",borderRadius:4,flexDirection:"row",flexWrap:"wrap",alignItems:"center",justifyContent:"center"},preview:{position:"absolute",width:164,height:32,textAlign:"center",textAlignVertical:"center",fontSize:18,backgroundColor:"#fff9db",color:"#c7a200"},commit:{position:"absolute",width:164,height:48,borderWidth:1,borderColor:"#ced4da",borderRadius:4,alignItems:"center",justifyContent:"center"},abs:{position:"absolute",borderWidth:1,borderRadius:4,alignItems:"center",justifyContent:"center"},memo:{position:"absolute",width:308,height:126,borderWidth:1,borderColor:"#ced4da",padding:8,textAlignVertical:"top"},bottomScore:{position:"absolute"},toast:{position:"absolute",backgroundColor:"#f03e5e",color:"white",padding:12,borderRadius:16,zIndex:20},scrim:{flex:1,backgroundColor:"#0008",alignItems:"center",justifyContent:"center",padding:24},dialog:{backgroundColor:"white",borderRadius:10,padding:20,width:"100%",maxWidth:540,maxHeight:"90%",gap:12},dialogTitle:{fontSize:21,fontWeight:"700"},row:{flexDirection:"row",gap:8,flexWrap:"wrap",marginVertical:6},pickRow:{padding:10,borderBottomWidth:1,borderColor:"#eee"}});
