import { useEffect, useMemo, useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { Redirect, useLocalSearchParams } from "expo-router";
import { useAuth } from "@/hooks/use-auth";
import { supabase } from "@/lib/supabase";
import { blank, Page, stateAt } from "@/lib/scoring/engine";
import { localStore, LocalGame } from "@/lib/scoring/local-store";
let JSON_CACHE:any[]=[];
export default function ScoringInput(){const {id=""}=useLocalSearchParams<{id:string}>();const {user,isLoading,hasRole}=useAuth();const [game,setGame]=useState<LocalGame|null>(null);const [pages,setPages]=useState<Page[]>([]);const [results,setResults]=useState<any[]>([]);const [teams,setTeams]=useState<any[]>([]);const [roster,setRoster]=useState<any[]>([]);const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{let local:LocalGame|undefined=(await localStore.games()).find(g=>g.id===id);if(!local){const {data}=await supabase.from("scoring_games").select("*").eq("id",id).single();if(data){const [{data:home},{data:away},{data:lineup}]=await Promise.all([supabase.from("opponent_teams").select("name").eq("id",data.home_team_id).single(),supabase.from("opponent_teams").select("name").eq("id",data.away_team_id).single(),supabase.from("scoring_lineups").select("*").eq("game_id",id)]);local={...data,home_name:home?.name,away_name:away?.name,lineup:lineup??[]} as LocalGame;await localStore.saveGames([local,...await localStore.games()])}}if(local){let ln=local.lineup as any[]|undefined;if(!ln?.length){const {data}=await supabase.from("scoring_lineups").select("*").eq("game_id",id);ln=data??[]}const enriched=await Promise.all((ln??[]).map(async(row:any)=>{if(row.player_snapshot?.name)return row;const {data}=await supabase.from("scoring_roster_players").select("id,name").eq("id",row.roster_player_id).single();return {...row,player_snapshot:data}}));local.lineup=enriched;setGame(local)}const stored=await localStore.plays(id);JSON_CACHE=stored;setPages(stored.map(p=>p.page));const [r,t,p]=await Promise.all([supabase.from("scoring_results").select("id,name,summary_code,engine_kind").eq("display_flag",true).order("show_index"),supabase.from("opponent_teams").select("id,name"),supabase.from("scoring_roster_players").select("id,name,team_id")]);setResults(r.data??[]);setTeams(t.data??[]);setRoster(p.data??[]);setLoading(false)})().catch(()=>setLoading(false))},[id]);
 const state=useMemo(()=>stateAt(pages.length,pages),[pages]);const batter=state.lu[state.half]?.order[state.bi[state.half]];const pitcher=state.lu[1-state.half]?.P;const lineup=game?.lineup as any[]|undefined;const activeTeam=state.half===0?game?.away_team_id:game?.home_team_id;const defenseTeam=state.half===0?game?.home_team_id:game?.away_team_id;const batterRow=lineup?.find(x=>x.team_id===activeTeam&&x.slot===state.bi[state.half]+1);const pitcherRow=lineup?.find(x=>x.team_id===defenseTeam&&x.slot===10);const batterName=batterRow?.player_snapshot?.name??roster.find(x=>x.id===batterRow?.roster_player_id)?.name??`#${batter??"?"}`;const pitcherName=pitcherRow?.player_snapshot?.name??roster.find(x=>x.id===pitcherRow?.roster_player_id)?.name??`#${pitcherRow?.uniform_no??"?"}`;
 if(isLoading||loading)return <View style={s.center}><Text>読み込み中…</Text></View>;if(!user)return <Redirect href="/login"/>;if(!hasRole("analyst")&&!hasRole("admin"))return <Redirect href="/(tabs)"/>;if(!game)return <View style={s.center}><Text>試合が見つかりません。</Text></View>;
 const commit=(result:any)=>{const page=blank();const ek=result.engine_kind;if(!ek)return;page.res={label:result.name,kind:/^[1-4]$/.test(ek)?Number(ek):ek};const next=[...pages,page];setPages(next);localStore.savePlay(id,page).then(saved=>{JSON_CACHE=saved}).catch(()=>{});};
 const undo=()=>{const next=pages.slice(0,-1);setPages(next);JSON_CACHE=JSON_CACHE.slice(0,next.length);localStore.savePlays(id,JSON_CACHE).catch(()=>{})};
 const finish=async()=>{const gs=await localStore.games();await localStore.saveGames(gs.map(g=>g.id===id?{...g,status:"draft"}:g));setGame({...game,status:"draft"});Alert.alert("保存しました","この端末に保存しました。試合管理から続けられます。")};
 return <ScrollView style={s.page} contentContainerStyle={s.wrap}><View style={s.head}><Text style={s.title}>{game.display_game_number}　試合記録</Text><Text>{game.game_date} · {game.status}</Text></View><View style={s.score}><Text style={s.scoreTitle}>{game.away_name??teams.find(t=>t.id===game.away_team_id)?.name??"先攻"}　{state.score[0]}　-　{state.score[1]}　{game.home_name??teams.find(t=>t.id===game.home_team_id)?.name??"後攻"}</Text><Text style={s.scoreSub}>{state.inn}回 {state.half===0?"表":"裏"}　{state.b}ボール {state.s}ストライク {state.outs}アウト</Text><Text style={s.scoreSub}>走者　一塁 {state.bases[0]??"－"}　|　二塁 {state.bases[1]??"－"}　|　三塁 {state.bases[2]??"－"}</Text></View><View style={s.card}><Text style={s.cardTitle}>打者 {batterName}　/　投手 {pitcherName}</Text><Text style={s.scoreSub}>プレイ {pages.length+1} · 保存は端末内で自動</Text></View><Text style={s.section}>結果</Text><View style={s.grid}>{results.map(r=><TouchableOpacity key={r.id} style={s.result} onPress={()=>commit(r)}><Text style={s.resultText}>{r.name}</Text></TouchableOpacity>)}</View><View style={s.row}><TouchableOpacity style={s.button} onPress={undo}><Text style={s.buttonText}>1つ戻す</Text></TouchableOpacity><TouchableOpacity style={s.button} onPress={finish}><Text style={s.buttonText}>保存して閉じる</Text></TouchableOpacity></View><Text style={s.note}>詳細な球種・コース・走者操作は第3段階で実装予定です。</Text></ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#f3f5f7"},wrap:{padding:20,gap:14,maxWidth:1200,width:"100%",alignSelf:"center"},center:{flex:1,alignItems:"center",justifyContent:"center"},head:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",flexWrap:"wrap"},title:{fontSize:24,fontWeight:"700",color:"#12314d"},score:{backgroundColor:"#102f4c",padding:20,borderRadius:12,gap:8},scoreTitle:{color:"white",fontSize:22,fontWeight:"700",textAlign:"center"},scoreSub:{color:"#d3e1ec",fontSize:16,textAlign:"center"},card:{backgroundColor:"white",padding:16,borderRadius:10},cardTitle:{fontSize:18,fontWeight:"700",textAlign:"center"},section:{fontSize:18,fontWeight:"700"},grid:{flexDirection:"row",flexWrap:"wrap",gap:8},result:{width:"23%",minWidth:110,minHeight:58,backgroundColor:"white",borderWidth:1,borderColor:"#cad5df",borderRadius:8,alignItems:"center",justifyContent:"center",padding:8},resultText:{fontWeight:"600",textAlign:"center"},row:{flexDirection:"row",gap:10,justifyContent:"center",flexWrap:"wrap"},button:{backgroundColor:"#0a7ea4",borderRadius:8,paddingVertical:12,paddingHorizontal:20},buttonText:{color:"white",fontWeight:"700"},note:{color:"#66798b",textAlign:"center"}});
