import { useCallback, useEffect, useState } from "react";
import { Alert, BackHandler, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { Redirect, router, useFocusEffect } from "expo-router";
import { useAuth } from "@/hooks/use-auth";
import { LocalGame, localStore } from "@/lib/scoring/local-store";
import { supabase } from "@/lib/supabase";
export default function ScoringHome(){const {user,isLoading,hasRole}=useAuth();const [games,setGames]=useState<LocalGame[]>([]),[teams,setTeams]=useState<any[]>([]),[players,setPlayers]=useState<any[]>([]);const [loading,setLoading]=useState(true);
 const refresh=async()=>{try{const local=await localStore.games();setGames(local);setLoading(false);
// 通信が切れていても画面を止めない。5秒で諦めて端末の控えを使う
const net=<T,>(q:PromiseLike<T>)=>Promise.race([Promise.resolve(q),new Promise<T>(r=>setTimeout(()=>r({data:null} as any),5000))]).catch(()=>({data:null}) as any);
const [{data:t},{data:p}]=await Promise.all([net(supabase.from("opponent_teams").select("id,name,is_own_team")),net(supabase.from("scoring_roster_players").select("id,team_id,retired"))]) as any[];if(t?.length){setTeams(t);await localStore.saveMasters("teams",t)}else setTeams(await localStore.masters("teams"));if(p?.length){setPlayers(p);await localStore.saveMasters("players",p)}else setPlayers(await localStore.masters("players"))}catch(e){console.warn("scoring refresh",e)}finally{setLoading(false)}};
 useFocusEffect(useCallback(()=>{refresh();return()=>{}},[]));
 useEffect(()=>{if(typeof window!=="undefined"&&typeof (window as any).addEventListener==="function"){const fn=()=>{refresh()};window.addEventListener("scoring-state-changed",fn);return()=>window.removeEventListener("scoring-state-changed",fn)}},[]);
 if(isLoading||loading)return <View style={s.center}><Text>読み込み中…</Text></View>;if(!user)return <Redirect href="/login"/>;if(!hasRole("analyst")&&!hasRole("admin"))return <Redirect href="/(tabs)"/>;
 const active=games.find(g=>g.status==="in_progress"),unsynced=games.filter(g=>!g.synced_at).length;const ownTeam=teams.find(t=>t.is_own_team);const ready=!!ownTeam&&teams.some(t=>t.id!==ownTeam.id)&&[ownTeam,...teams.filter(t=>t.id!==ownTeam.id)].every(t=>players.filter(p=>p.team_id===t.id&&!p.retired).length>=9);
 const reset=()=>Alert.alert("入力をリセットしますか？","記録済みのプレイは残し、試合を保存済みにします。",[{text:"キャンセル",style:"cancel"},{text:"リセット",style:"destructive",onPress:async()=>{if(!active)return;const next=games.map(g=>g.id===active.id?{...g,status:"suspended" as const}:g);await localStore.saveGames(next);setGames(next)}}]);
 return <ScrollView style={s.page} contentContainerStyle={s.wrap}><Text style={s.title}>試合記録</Text><View style={s.badge}><Text style={s.badgeText}>未同期 {unsynced}試合</Text></View>{(!teams.length||!ready)&&<View style={s.guidance}><Text style={s.guidanceTitle}>まずチームと選手を登録しましょう</Text><Text style={s.sub}>試合を始めるには、チームごとに現役選手を9人以上登録してください。</Text><TouchableOpacity style={s.guidanceButton} onPress={()=>router.push("/scoring/masters" as any)}><Text style={s.guidanceText}>マスター管理へ</Text></TouchableOpacity></View>}
 <TouchableOpacity style={s.choice} onPress={()=>router.push("/scoring/manage" as any)}><Text style={s.choiceTitle}>試合管理</Text><Text style={s.choiceSub}>保存した試合の確認・編集・同期</Text></TouchableOpacity>
 <View style={s.middle}><TouchableOpacity disabled={!active&&!ready} style={[s.choice,s.middleChoice,(!active&&!ready)&&s.disabled]} onPress={()=>active?router.push(`/scoring/${active.id}` as any):router.push("/scoring/create" as any)}><Text style={s.choiceTitle}>{active?"試合入力を再開":"新規試合入力"}</Text><Text style={s.choiceSub}>{!active&&!ready?"チームごとに選手を9人登録してください":active?`${active.display_game_number}　${active.away_name} vs ${active.home_name}`:"試合情報と先発メンバーを入力します"}</Text></TouchableOpacity>{active&&<TouchableOpacity style={s.reset} onPress={reset}><Text style={s.resetText}>リセット</Text></TouchableOpacity>}</View>
 <TouchableOpacity style={s.choice} onPress={()=>router.push("/scoring/masters" as any)}><Text style={s.choiceTitle}>マスター管理</Text><Text style={s.choiceSub}>チーム・選手・球場などを登録</Text></TouchableOpacity></ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#f4f6f8"},wrap:{padding:22,gap:14,maxWidth:900,width:"100%",alignSelf:"center"},center:{flex:1,alignItems:"center",justifyContent:"center"},title:{fontSize:30,fontWeight:"700",color:"#132b45"},badge:{alignSelf:"flex-end",backgroundColor:"#e7f5ff",paddingHorizontal:12,paddingVertical:7,borderRadius:20},badgeText:{color:"#1864ab",fontWeight:"700"},choice:{backgroundColor:"white",borderWidth:1,borderColor:"#d7e0e7",borderRadius:14,padding:22,minHeight:100,justifyContent:"center"},middle:{flexDirection:"row",alignItems:"center",gap:8},middleChoice:{flex:1},choiceTitle:{fontSize:22,fontWeight:"700",color:"#132b45"},choiceSub:{fontSize:14,color:"#65788a",marginTop:5},disabled:{opacity:.55},guidance:{backgroundColor:"#fff3bf",padding:16,borderRadius:10,gap:8},guidanceTitle:{fontWeight:"700",fontSize:18,color:"#664d03"},sub:{color:"#65788a"},guidanceButton:{alignSelf:"flex-start",backgroundColor:"#0a7ea4",padding:10,borderRadius:7},guidanceText:{color:"white",fontWeight:"700"},reset:{padding:12,borderWidth:1,borderColor:"#e03131",borderRadius:7},resetText:{color:"#c92a2a",fontWeight:"700"}});
