import { useEffect, useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { Redirect, router } from "expo-router";
import { useAuth } from "@/hooks/use-auth";
import { localStore, LocalGame } from "@/lib/scoring/local-store";
import { syncScoringGame } from "@/lib/scoring/sync-game";
import { supabase } from "@/lib/supabase";
export default function ManageGames(){const {user,isLoading,hasRole}=useAuth();const [games,setGames]=useState<LocalGame[]>([]),[busy,setBusy]=useState(false);
 const refresh=async()=>{const local=await localStore.games();const {data}=await supabase.from("scoring_games").select("*").order("game_date",{ascending:false}).limit(100);const merged=[...local,...(data??[]).filter((r:any)=>!local.some(g=>g.id===r.id)).map((r:any)=>({...r,lineup:[]} as LocalGame))];setGames(merged);};useEffect(()=>{refresh()},[]);
 if(isLoading)return <View style={s.center}><Text>読み込み中…</Text></View>;if(!user)return <Redirect href="/login"/>;if(!hasRole("analyst")&&!hasRole("admin"))return <Redirect href="/(tabs)"/>;
 const sync=async(g:LocalGame)=>{setBusy(true);try{await syncScoringGame(g,user.id);Alert.alert("同期しました");}catch{Alert.alert("同期できません","通信状態と必要な権限を確認してください")}finally{setBusy(false)}};
 return <ScrollView style={s.page} contentContainerStyle={s.wrap}><TouchableOpacity onPress={()=>router.back()}><Text style={s.link}>‹ 試合記録に戻る</Text></TouchableOpacity><Text style={s.title}>試合管理</Text>{games.length===0&&<Text style={s.sub}>端末に保存された試合はありません。</Text>}{games.map(g=><View key={g.id} style={s.card}><View style={{flex:1}}><Text style={s.name}>{g.display_game_number}　{g.game_date}</Text><Text style={s.sub}>{g.away_name??"先攻"}（先攻） vs {g.home_name??"後攻"}（後攻）</Text><Text style={s.sub}>{g.score_away!=null?`${g.score_away} - ${g.score_home}　`:""}{g.synced_at?"同期済み":"未同期"}　·　{g.status==="suspended"?"保存済み":g.status==="in_progress"?"入力中":"完了"}</Text></View><TouchableOpacity style={s.button} onPress={()=>router.push(`/scoring/${g.id}` as any)}><Text>編集／再開</Text></TouchableOpacity><TouchableOpacity style={s.button} disabled={busy||!!g.synced_at} onPress={()=>sync(g)}><Text>{g.synced_at?"同期済み":"同期"}</Text></TouchableOpacity></View>)}</ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#f4f6f8"},wrap:{padding:20,gap:12,maxWidth:1000,width:"100%",alignSelf:"center"},center:{flex:1,alignItems:"center",justifyContent:"center"},title:{fontSize:28,fontWeight:"700",color:"#132b45"},card:{backgroundColor:"white",borderWidth:1,borderColor:"#e1e6eb",borderRadius:10,padding:14,flexDirection:"row",alignItems:"center",gap:8},name:{fontWeight:"700",fontSize:16},sub:{color:"#65788a",marginTop:4},button:{borderColor:"#0a7ea4",borderWidth:1,borderRadius:7,padding:10},link:{color:"#0a7ea4"}});
