import { failAfter, withTimeout } from "@/lib/scoring/net";
import { deleteScoringGame } from "@/lib/scoring/delete-game";
import { useCallback, useEffect, useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { Redirect, router, useFocusEffect } from "expo-router";
import { useAuth } from "@/hooks/use-auth";
import { localStore, LocalGame } from "@/lib/scoring/local-store";
import { syncScoringGame } from "@/lib/scoring/sync-game";
import { supabase } from "@/lib/supabase";
import * as FileSystem from "expo-file-system/legacy";
import * as Sharing from "expo-sharing";
import { export191Game, export191Sheet, legacyFileName } from "@/lib/scoring/export191";
import * as XLSX from "xlsx";
export default function ManageGames(){const {user,isLoading,hasRole}=useAuth();const [games,setGames]=useState<LocalGame[]>([]),[busy,setBusy]=useState<string|null>(null),[errors,setErrors]=useState<Record<string,string>>({});
 // 端末の試合をすぐ出し、サーバーの試合は届いたら足す（通信が遅い・切れていても一覧が空にならない）
const refresh=async()=>{const local=await localStore.games();setGames(local);const res:any=await Promise.race([Promise.resolve(supabase.from("scoring_games").select("*").order("game_date",{ascending:false}).limit(100)),new Promise(r=>setTimeout(()=>r({data:null}),5000))]).catch(()=>({data:null}));const data=res?.data;const merged=[...local,...(data??[]).filter((r:any)=>!local.some(g=>g.id===r.id)).map((r:any)=>({...r,lineup:[],synced_at:r.updated_at??r.created_at??"server",remoteOnly:true} as LocalGame))];setGames(merged);};useEffect(()=>{refresh()},[]);
 // 画面に戻ってきたときも読み直す
 useFocusEffect(useCallback(()=>{refresh()},[]));
 if(isLoading)return <View style={s.center}><Text>読み込み中…</Text></View>;if(!user)return <Redirect href="/login"/>;if(!hasRole("analyst")&&!hasRole("admin"))return <Redirect href="/(tabs)"/>;
 // 削除：確認してから。サーバーにある試合（同期したことがある・別の端末の試合）はサーバーからも消す
 const remove=(g:LocalGame)=>{const onServer=Boolean((g as any).remoteOnly||(g as any).ever_synced||g.synced_at);
  Alert.alert("試合を削除しますか？",`${g.display_game_number}　${g.away_name??"先攻"} vs ${g.home_name??"後攻"}\n${onServer?"試合結果からも消え、部員全員の画面から見えなくなります。":"この端末から消えます。"}元に戻せません。`,[{text:"キャンセル",style:"cancel"},{text:"削除",style:"destructive",onPress:async()=>{setBusy(g.id);setErrors(v=>({...v,[g.id]:""}));try{await deleteScoringGame(g.id,supabase,onServer);setGames(cur=>cur.filter(x=>x.id!==g.id))}catch(error){setErrors(v=>({...v,[g.id]:error instanceof Error?error.message:"削除できませんでした"}))}finally{setBusy(null)}}}])};
 const sync=async(g:LocalGame)=>{setBusy(g.id);setErrors(v=>({...v,[g.id]:""}));try{await failAfter(syncScoringGame(g,user.id,supabase),60000,"サーバーにつながりませんでした。電波のある所でもう一度「同期」を押してください（入力した記録は端末に残っています）");const next=await localStore.games();setGames(current=>current.map(row=>next.find(x=>x.id===row.id)??row));setErrors(v=>({...v,[g.id]:""}));}catch(error){const message=error instanceof Error?error.message:"原因を確認できませんでした";setErrors(v=>({...v,[g.id]:message}))}finally{setBusy(null)}};
 const exportGame=async(g:LocalGame)=>{setBusy(g.id);setErrors(v=>({...v,[g.id]:""}));try{let lineup=(g.lineup??[]) as any[];if(!lineup.length){const {data,error}=await withTimeout(supabase.from("scoring_lineups").select("*").eq("game_id",g.id));if(error)throw new Error("この試合の打順が端末になく、サーバーにもつながりませんでした");lineup=data??[];const ids=lineup.map(r=>r.roster_player_id).filter(Boolean);if(ids.length){const {data:players,error:playerError}=await supabase.from("scoring_roster_players").select("id,name,bat_hand,throw_hand,show_index").in("id",ids);if(playerError)throw playerError;lineup=lineup.map(r=>({...r,player_snapshot:(players??[]).find(p=>p.id===r.roster_player_id)}));}}
 const local=await localStore.plays(g.id);let plays=local;if(!plays.length&&g.synced_at){const {data,error}=await supabase.from("scoring_plays").select("seq,input_event").eq("game_id",g.id).order("seq");if(error)throw error;plays=(data??[]).map(r=>({seq:r.seq,page:r.input_event} as any));}
 const [teams,ballTypes,roster,careers]=await Promise.all([localStore.masters("teams"),localStore.masters("ballTypes"),withTimeout(supabase.from("scoring_roster_players").select("id,team_id,name,show_index").in("team_id",[g.away_team_id,g.home_team_id])),withTimeout(supabase.from("scoring_player_careers").select("roster_player_id,team_id,uniform_no").in("team_id",[g.away_team_id,g.home_team_id]).is("end_date",null))]);
 // 電波がなければ、入力画面が控えた選手と背番号で書き出す
 const mine=(rows:any[])=>rows.filter(r=>r.team_id===g.away_team_id||r.team_id===g.home_team_id);if(roster.error||!roster.data)(roster as any).data=mine(await localStore.masters("input:players") as any[]);if(careers.error||!careers.data)(careers as any).data=mine(await localStore.masters("input:careers") as any[]);const players=(roster.data??[]).map(p=>({...p,uniform_no:careers.data?.find(c=>c.roster_player_id===p.id)?.uniform_no}));const home=teams.find(t=>String(t.id)===g.home_team_id);const away=teams.find(t=>String(t.id)===g.away_team_id);const info=export191Game({...g,home_name:g.home_name??String(home?.name??""),away_name:g.away_name??String(away?.name??"")} as any,lineup,plays, {ballTypes:ballTypes as any,players});// 旧Excelと同じ名前・同じ形のExcelで書き出す
const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(export191Sheet(info)),"試合記録");const b64=XLSX.write(wb,{type:"base64",bookType:"xlsx"});
const fileName=legacyFileName({...g,home_name:g.home_name??String(home?.name??""),away_name:g.away_name??String(away?.name??"")}).replace(/[\/:*?"<>|]/g,"_");if(!FileSystem.documentDirectory)throw new Error("書類フォルダを利用できません");const uri=`${FileSystem.documentDirectory}${fileName}`;await FileSystem.writeAsStringAsync(uri,b64,{encoding:FileSystem.EncodingType.Base64});if(await Sharing.isAvailableAsync())await Sharing.shareAsync(uri,{mimeType:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",dialogTitle:"試合記録を書き出す",UTI:"org.openxmlformats.spreadsheetml.sheet"});else setErrors(v=>({...v,[g.id]:`保存しました: ${uri}`}));}catch(error){setErrors(v=>({...v,[g.id]:error instanceof Error?error.message:"書き出しに失敗しました"}))}finally{setBusy(null)}};
 return <ScrollView style={s.page} contentContainerStyle={s.wrap}><TouchableOpacity onPress={()=>router.back()}><Text style={s.link}>‹ 試合記録に戻る</Text></TouchableOpacity><Text style={s.title}>試合管理</Text>{games.length===0&&<Text style={s.sub}>端末に保存された試合はありません。</Text>}{games.map(g=><View key={g.id} style={s.card}><View style={{flex:1}}><Text style={s.name}>{g.display_game_number}　{g.game_date}</Text><Text style={s.sub}>{g.away_name??"先攻"}（先攻） vs {g.home_name??"後攻"}（後攻）</Text><Text style={s.sub}>{g.score_away!=null?`${g.score_away} - ${g.score_home}　`:""}{(g as any).remoteOnly?"別の端末で入力":g.synced_at?"同期済み":"未同期"}　·　{g.status==="suspended"?"保存済み":g.status==="in_progress"?"入力中":"完了"}</Text>{!!errors[g.id]&&<Text style={s.error}>{errors[g.id].startsWith("保存しました:")?errors[g.id]:`同期／出力エラー: ${errors[g.id]}`}</Text>}</View>{!(g as any).remoteOnly&&<TouchableOpacity style={s.button} onPress={()=>router.push((g.status==="completed"?`/scoring/${g.id}?edit=1`:`/scoring/${g.id}`) as any)}><Text>編集／再開</Text></TouchableOpacity>}<TouchableOpacity style={s.button} disabled={busy!==null} onPress={()=>exportGame(g)}><Text>{busy===g.id?"処理中…":"Excelで書き出す"}</Text></TouchableOpacity><TouchableOpacity style={s.button} disabled={busy!==null||!!g.synced_at} onPress={()=>sync(g)}><Text>{busy===g.id?"同期中…":g.synced_at?"同期済み":"同期"}</Text></TouchableOpacity><TouchableOpacity style={[s.button,{borderColor:"#e03131"}]} disabled={busy!==null} onPress={()=>remove(g)}><Text style={{color:"#e03131"}}>削除</Text></TouchableOpacity></View>)}</ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#f4f6f8"},wrap:{padding:20,gap:12,maxWidth:1000,width:"100%",alignSelf:"center"},center:{flex:1,alignItems:"center",justifyContent:"center"},title:{fontSize:28,fontWeight:"700",color:"#132b45"},card:{backgroundColor:"white",borderWidth:1,borderColor:"#e1e6eb",borderRadius:10,padding:14,flexDirection:"row",alignItems:"center",gap:8},name:{fontWeight:"700",fontSize:16},sub:{color:"#65788a",marginTop:4},error:{color:"#c92a2a",marginTop:6},button:{borderColor:"#0a7ea4",borderWidth:1,borderRadius:7,padding:10},link:{color:"#0a7ea4"}});
