import { useEffect, useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { Redirect, router, useLocalSearchParams } from "expo-router";
import { useAuth } from "@/hooks/use-auth";
import { supabase } from "@/lib/supabase";
import { localStore } from "@/lib/scoring/local-store";
const tableMap: Record<string,string>={チーム:"opponent_teams",選手:"scoring_roster_players",球場:"scoring_stadiums",カテゴリ:"scoring_categories",球種:"scoring_ball_types",結果:"scoring_results",作戦:"scoring_plans",メモ:"scoring_memos"};
const fields:Record<string,string[]>={チーム:["name","name_s","name_e","name_es","mark","is_own_team"],選手:["team_id","name","name_s","throw_hand","bat_hand","pitching_form","primary_position_id","retired"],球場:["name","name_s","capacity","left_distance","center_distance","right_distance"],カテゴリ:["name","name_s","name_e","kind"],球種:["name","name_s","symbol","family_id","stats_kind"],結果:["id","name","name_s","summary_code","old_excel_label"],作戦:["id","name","name_s","division","old_excel_label"],メモ:["id","name","division"]};
export default function MasterForm(){const {kind="チーム",id}=useLocalSearchParams<{kind:string;id?:string}>();const {user,isLoading,hasRole}=useAuth();const [values,setValues]=useState<Record<string,string>>({});const [career,setCareer]=useState("");const [aliases,setAliases]=useState("");const [positions,setPositions]=useState("1");const [uniform,setUniform]=useState("");const table=tableMap[kind]??"opponent_teams";const editable=fields[kind]??fields.チーム;
 useEffect(()=>{if(id)supabase.from(table).select("*").eq("id",id).maybeSingle().then(({data})=>{if(data)setValues(Object.fromEntries(editable.map(k=>[k,data[k]==null?"":String(data[k])])))});},[id,kind]);
 if(isLoading)return <View style={s.wrap}><Text>読み込み中</Text></View>;if(!user)return <Redirect href="/login"/>;if(!hasRole("analyst")&&!hasRole("admin"))return <Redirect href="/(tabs)"/>;
 const save=async()=>{const data:any={};for(const k of editable){if(values[k]!==undefined){const v=values[k];data[k]=["is_own_team","retired"].includes(k)?v.toLowerCase()==="true":(["id","primary_position_id","capacity","left_distance","center_distance","right_distance","family_id","stats_kind","division"].includes(k)&&v!==""?Number(v):v||null)}}if(kind==="選手"&&!id)data.show_index=0;let playerId=String(id??"");if(id){const result=await supabase.from(table).update(data).eq("id",id);if(result.error){Alert.alert("保存できません",result.error.message);return}}else if(kind==="選手"){const {data:created,error}=await supabase.from(table).insert(data).select("id").single();if(error){Alert.alert("保存できません",error.message);return}playerId=created.id}else{const result=await supabase.from(table).insert(data);if(result.error){Alert.alert("保存できません",result.error.message);return}}if(kind==="選手"&&playerId){await supabase.from("scoring_player_careers").delete().eq("roster_player_id",playerId);if(uniform.trim())await supabase.from("scoring_player_careers").insert({roster_player_id:playerId,team_id:data.team_id,start_date:new Date().toISOString().slice(0,10),uniform_no:uniform.trim()});for(const row of career.split("\n").filter(Boolean)){const [team_id,start_date,end_date,uniform_no]=row.split(",");await supabase.from("scoring_player_careers").insert({roster_player_id:playerId,team_id,start_date:start_date||null,end_date:end_date||null,uniform_no:uniform_no||null})}await supabase.from("scoring_name_aliases").delete().eq("roster_player_id",playerId);for(const alias of aliases.split("\n").map(x=>x.trim()).filter(Boolean))await supabase.from("scoring_name_aliases").insert({roster_player_id:playerId,alias})}const kindKey=kind==="チーム"?"teams":kind==="選手"?"players":kind==="球場"?"stadiums":"";if(kindKey){const {data:rows}=await supabase.from(table).select("*").limit(500);if(rows)await localStore.saveMasters(kindKey,rows)}Alert.alert("保存しました");router.back()};
 const disable=async()=>{const result=await supabase.from(table).update(kind==="選手"?{retired:true}:kind==="チーム"?{display_order:null}:{display_flag:false}).eq("id",id);if(result.error)Alert.alert("無効化できません",result.error.message);else router.back()};
 return <ScrollView style={s.page} contentContainerStyle={s.wrap}><Text style={s.title}>{id?`${kind}を編集`:`${kind}を追加`}</Text>{editable.map(k=><View key={k}><Text style={s.label}>{k}</Text><TextInput style={s.input} value={values[k]??""} onChangeText={v=>setValues({...values,[k]:v})} placeholder={k==="team_id"?"チームID":""} keyboardType={/[0-9]$/.test(k)?"numeric":"default"}/></View>)}{kind==="選手"&&<><Text style={s.label}>現在の背番号</Text><TextInput style={s.input} value={uniform} onChangeText={setUniform} keyboardType="numeric"/><Text style={s.label}>経歴（team_id,開始日,終了日,背番号を1行ずつ）</Text><TextInput style={[s.input,s.multi]} multiline value={career} onChangeText={setCareer}/><Text style={s.label}>旧Excel名の別名（1行ずつ）</Text><TextInput style={[s.input,s.multi]} multiline value={aliases} onChangeText={setAliases}/></> }<TouchableOpacity style={s.button} onPress={save}><Text style={s.buttonText}>保存</Text></TouchableOpacity>{id&&<TouchableOpacity style={s.disable} onPress={disable}><Text>無効化</Text></TouchableOpacity>}</ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#f4f6f8"},wrap:{padding:20,gap:12,maxWidth:900,width:"100%",alignSelf:"center"},title:{fontSize:24,fontWeight:"700"},label:{fontWeight:"600",color:"#34495e"},input:{backgroundColor:"white",borderWidth:1,borderColor:"#ccd5de",borderRadius:7,padding:12,minHeight:44},multi:{minHeight:88},button:{backgroundColor:"#0a7ea4",borderRadius:8,padding:14,alignItems:"center"},buttonText:{color:"white",fontWeight:"700"},disable:{padding:12,alignItems:"center",borderWidth:1,borderColor:"#b66",borderRadius:8}});
